### ISSUE TITLE
Does Not Build for visionOS

### ISSUE THREAD

**Issue by bwake2012** [divadretlaw/WindowSceneReader#1]
Xcode reports “Cannot call value of non-function type 'module<WindowSceneReader>'” for a visionOS target.

Demo at:   https://github.com/bwake2012/WindowSceneReaderDemo.git

It builds just fine for iOS/iPadOS and macOS. 

What am I missing?

**Comment by divadretlaw** [comment]
Hi, visionOS wasn't really supported by `WindowReader` and `WindowSceneReader` but I updated them to include visionOS support.

Please use the new version `3.0.0` for it to work with visionOS too. Please let me know if any other issue occurs using the new version, thank you.

**Comment by bwake2012** [comment]
I thought I read in your readme that it did. Perhaps I was mistaken.
